# Generated by Django 3.2.8 on 2021-10-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('category', models.SmallIntegerField(choices=[(1, 'PIZZA'), (2, 'KEBAB'), (3, 'BURGERS'), (4, 'SALADS'), (5, 'DRINKS')])),
                ('size_and_cost', models.JSONField()),
                ('description', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='media')),
            ],
        ),
    ]
