# Generated by Django 3.2.8 on 2021-10-15 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='size_and_cost',
        ),
        migrations.AddField(
            model_name='food',
            name='cost',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='size',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
