# Generated by Django 3.2.8 on 2021-10-16 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaApp', '0002_auto_20211016_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
